<?php

use yii\bootstrap4\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Table3 */

$this->title = 'Месяц '.Yii::$app->myComponent->monthsLearningShort(
        $model->month_status
    ).', за учебный год '.Yii::$app->myComponent->yearStudy(
        $model->year_study
    );
$this->params['breadcrumbs'][] = ['label' => 'Table3s', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="table3-view container">


    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'year_study',
            [
                'attribute' => 'month_status',
                'value' => function ($model) {
                    return Yii::$app->myComponent->monthsLearning($model->month_status);
                },
            ],
            'total_organizations',
            'field1_1',
            'field1_2',
            'field1_3',
            'field1',
            'field2',
            'field3',
            'field4',
            'field5',
            'field6',
            'field7',
            'field8',
            'field9',
            'field10',
            'field11',
            'field12',
            'field13',
            'field14',
            'field15',
            'field16',
            'field17',
            'field18',
            'field19',
            'field20',
            'field21',
            'field22',
            'field23',
            'field24',
            'field25',
            'field26',
            'field27',
            'field28',
            'field29',
            'field30',
            'field31',
            'field32',
            'field33',
            'field34',
            'field35',
            'field36',
            'field37',
            'field38',
            'field39',
            'field40',
            'field41',
            'field42',
            'field43',
            'field44',
            'field45',
            'field46',
            'field47',
            'field48',
            'field49',
            'field50',
            'field51',
            'field52',
            'field53',
            'field54',
            'field55',
            'field56',
            'field57',
            'field58',
            'field59',
            'field60',
            'field61',
            'field62',
            'field63',
            'field64',
            'field65',
            'field66',
            'field67',
            'field68',
            'field69',
            'field70',
            'field71',
            'field72',
            'field73',
            'field74',
            'field74_1',
            'field74_2',
            'field75',
            'field76',
            'field77',
            'field78',
            'field79',
            'field80',
            'field81',
            'field82',
            'field83',
            'field84',
            'field85',
            'field86',
            'field87',
            'field88',
            'field89',
            'field90',
            'field91',
            'field92',
            'field93',
            'field94',
            'field95',
            'field96',
            'field97',
            'field98',
            'field99',
            'field100',
            'field101',
            'field102',
            'field103',
            'field104',
            'field105',
            'field106',
            'field107',
            'field108',
            'field109',
            'field110',
            'field111',
            'field112',
            'field113',
            'field114',
            'field115',
            'field116',
            'field117',
            'field118',
            'field119',
            'field120',
            'field121',
            'field122',
            'field123',
            'field124',
            'field125',
            'field126',
            'field127',
            'field128',
            'field129',
            'field130',
            'field131',
            'field132',
            'field133',
            'field134',
            'field135',
            'field136',
            'field137',
            'field138',
            'field139',
            'field140',
            'field141',
            'field142',
            'field143',
            'field144',
            'field145',
            'field146',
            'field147',
            'field148',
            'field149',
            'field150',
            'field151',
            'field152',
            'field153',
            'field154',
            'field155',
            'field156',
            'field157',
            'field158',
            'field159',
            'field160',
            'field161',
            'field162',
            'field163',
            'field164',
            'field165',
            'field166',
        ],
    ]) ?>

</div>
